serial: monte_carlo_serial.cpp
	g++ -fopenmp -o mc_serial monte_carlo_serial.cpp
omp: monte_carlo_omp.cpp
	g++ -fopenmp -o mc_omp monte_carlo_omp.cpp
acc: monte_carlo_acc.cpp
	???
clean:
	rm -f mc_serial mc_omp *~